# Generated by Django 5.1.7 on 2025-03-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cifrasapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chords',
            name='key',
            field=models.CharField(max_length=3),
        ),
    ]
