# Generated by Django 5.1.7 on 2025-03-17 00:31

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cifrasapp', '0002_alter_chords_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='chords',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
