# Generated by Django 5.1.7 on 2025-03-17 01:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cifrasapp', '0003_chords_published_date_alter_label_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chords',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
